import React, { useState } from "react";
import {
  Sparkles,
  Check,
  Copy,
  Download,
  ShieldCheck,
  AlertTriangle,
  Code2,
  CheckCircle2,
  FileCode,
  ExternalLink,
  ChevronRight,
} from "lucide-react";
import { FixSuggestion, PotentialRisk } from "../types";

interface FixSuggestionModalProps {
  isOpen: boolean;
  onClose: () => void;
  risk: PotentialRisk | null;
  suggestion: FixSuggestion | null;
  isLoading: boolean;
  language: "vi" | "en";
  diffContent?: string;
}

export const FixSuggestionModal: React.FC<FixSuggestionModalProps> = ({
  isOpen,
  onClose,
  risk,
  suggestion,
  isLoading,
  language,
  diffContent,
}) => {
  const [copiedCode, setCopiedCode] = useState(false);
  const [copiedTest, setCopiedTest] = useState(false);
  const [activeTab, setActiveTab] = useState<"fix" | "test" | "reasoning">("fix");

  if (!isOpen) return null;

  const handleCopyCode = () => {
    if (!suggestion?.suggestedCode) return;
    navigator.clipboard.writeText(suggestion.suggestedCode);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const handleCopyTest = () => {
    if (!suggestion?.testCode) return;
    navigator.clipboard.writeText(suggestion.testCode);
    setCopiedTest(true);
    setTimeout(() => setCopiedTest(false), 2000);
  };

  const handleDownloadPatch = () => {
    if (!suggestion?.suggestedCode) return;
    const patchText = `From: PatchWise AI Fix Generator <ai@patchwise.internal>
Subject: [PATCH] Fix ${risk?.category || "security issue"}: ${risk?.description || "automated vulnerability fix"}

---
${suggestion.suggestedCode}
-- 
Generated by PatchWise AI (Confidence: ${Math.round((suggestion.confidenceScore || 0.95) * 100)}%)
`;
    const blob = new Blob([patchText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `fix_${(risk?.category || "patch").toLowerCase().replace(/[^a-z0-9]/g, "_")}.patch`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-6 animate-in fade-in">
      <div className="bg-zinc-900 border border-zinc-800 rounded-2xl max-w-4xl w-full max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="p-5 border-b border-zinc-800 bg-zinc-950/80 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-emerald-600 via-teal-500 to-indigo-600 p-[1px] shadow-lg shadow-emerald-950/50">
              <div className="w-full h-full bg-zinc-950 rounded-[11px] flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-emerald-400" />
              </div>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base sm:text-lg font-bold text-white tracking-tight">
                  {language === "vi" ? "Đề xuất Bản vá Tự động (Auto-Fix Suggestion)" : "AI Auto-Fix Suggestion"}
                </h3>
                {suggestion && (
                  <span className="px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 text-[10px] font-mono">
                    {Math.round((suggestion.confidenceScore || 0.95) * 100)}% Confidence
                  </span>
                )}
              </div>
              <p className="text-xs text-zinc-400">
                {language === "vi"
                  ? "Tạo mã nguồn đã khắc phục lỗ hổng kèm bài kiểm thử đơn vị"
                  : "Automated vulnerability mitigation and unit test generation"}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-zinc-400 hover:text-white bg-zinc-900 border border-zinc-800 hover:border-zinc-700 transition cursor-pointer text-sm"
          >
            ✕
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {/* Target Risk Context */}
          {risk && (
            <div className="p-3.5 rounded-xl bg-zinc-950 border border-zinc-800 flex items-start gap-3">
              <div className="p-1.5 rounded-lg bg-rose-500/10 text-rose-400 border border-rose-500/20 shrink-0 mt-0.5">
                <AlertTriangle className="w-4 h-4" />
              </div>
              <div className="space-y-0.5">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded uppercase bg-rose-500/20 text-rose-300 border border-rose-500/30">
                    {risk.category}
                  </span>
                  <span className="text-xs text-zinc-400 font-mono">Mức độ: {risk.severity}</span>
                </div>
                <p className="text-xs text-zinc-200">{risk.description}</p>
              </div>
            </div>
          )}

          {isLoading ? (
            <div className="py-16 flex flex-col items-center justify-center gap-3 text-center">
              <div className="w-8 h-8 rounded-full border-2 border-emerald-500/20 border-t-emerald-500 animate-spin" />
              <p className="text-sm text-zinc-300 font-medium">
                {language === "vi" ? "Gemini đang tổng hợp bản vá an toàn & unit test..." : "Synthesizing secure patch & unit tests..."}
              </p>
              <p className="text-xs text-zinc-500">
                {language === "vi" ? "Phân tích logic nhánh code và loại bỏ rủi ro bảo mật" : "Auditing code flow and mitigating edge-cases"}
              </p>
            </div>
          ) : suggestion ? (
            <div className="space-y-4">
              {/* Tab Selector */}
              <div className="flex items-center gap-2 border-b border-zinc-800 pb-2">
                <button
                  onClick={() => setActiveTab("fix")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition cursor-pointer flex items-center gap-1.5 ${
                    activeTab === "fix"
                      ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40"
                      : "text-zinc-400 hover:text-zinc-200 bg-zinc-900/50"
                  }`}
                >
                  <FileCode className="w-3.5 h-3.5" />
                  <span>{language === "vi" ? "Mã nguồn đã sửa (Fixed Code)" : "Patched Code"}</span>
                </button>

                <button
                  onClick={() => setActiveTab("test")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition cursor-pointer flex items-center gap-1.5 ${
                    activeTab === "test"
                      ? "bg-indigo-500/20 text-indigo-300 border border-indigo-500/40"
                      : "text-zinc-400 hover:text-zinc-200 bg-zinc-900/50"
                  }`}
                >
                  <ShieldCheck className="w-3.5 h-3.5" />
                  <span>{language === "vi" ? "Bài kiểm thử (Unit Test)" : "Unit Tests"}</span>
                </button>

                <button
                  onClick={() => setActiveTab("reasoning")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition cursor-pointer flex items-center gap-1.5 ${
                    activeTab === "reasoning"
                      ? "bg-teal-500/20 text-teal-300 border border-teal-500/40"
                      : "text-zinc-400 hover:text-zinc-200 bg-zinc-900/50"
                  }`}
                >
                  <Code2 className="w-3.5 h-3.5" />
                  <span>{language === "vi" ? "Giải thích kỹ thuật" : "Technical Reasoning"}</span>
                </button>
              </div>

              {/* TAB 1: Fixed Code */}
              {activeTab === "fix" && (
                <div className="space-y-3">
                  <div className="relative rounded-xl bg-zinc-950 border border-zinc-800 p-4 font-mono text-xs text-zinc-200 overflow-x-auto">
                    <div className="flex items-center justify-between pb-2 mb-2 border-b border-zinc-800/80 text-[11px] text-zinc-400">
                      <span className="text-emerald-400 flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        {language === "vi" ? "Đã áp dụng quy tắc phòng vệ (Defensive Coding)" : "Defensive patch generated"}
                      </span>
                      <div className="flex items-center gap-2">
                        <button
                          onClick={handleCopyCode}
                          className="flex items-center gap-1 px-2.5 py-1 rounded bg-zinc-900 hover:bg-zinc-800 text-zinc-300 border border-zinc-700 text-[11px] transition cursor-pointer"
                        >
                          {copiedCode ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                          <span>{copiedCode ? "Đã sao chép" : "Sao chép mã"}</span>
                        </button>
                        <button
                          onClick={handleDownloadPatch}
                          className="flex items-center gap-1 px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-white font-sans text-[11px] transition cursor-pointer shadow-sm"
                        >
                          <Download className="w-3 h-3" />
                          <span>Tải file .patch</span>
                        </button>
                      </div>
                    </div>
                    <pre className="text-emerald-300/90 whitespace-pre-wrap leading-relaxed">
                      {suggestion.suggestedCode}
                    </pre>
                  </div>
                </div>
              )}

              {/* TAB 2: Unit Test */}
              {activeTab === "test" && (
                <div className="space-y-3">
                  <div className="relative rounded-xl bg-zinc-950 border border-zinc-800 p-4 font-mono text-xs text-zinc-200 overflow-x-auto">
                    <div className="flex items-center justify-between pb-2 mb-2 border-b border-zinc-800/80 text-[11px] text-zinc-400">
                      <span className="text-indigo-400 flex items-center gap-1">
                        <ShieldCheck className="w-3.5 h-3.5" />
                        {language === "vi" ? "Test Case chứng minh lỗ hổng đã được bịt kín" : "Automated Regression Test"}
                      </span>
                      <button
                        onClick={handleCopyTest}
                        className="flex items-center gap-1 px-2.5 py-1 rounded bg-zinc-900 hover:bg-zinc-800 text-zinc-300 border border-zinc-700 text-[11px] transition cursor-pointer"
                      >
                        {copiedTest ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                        <span>{copiedTest ? "Đã chép test" : "Sao chép Unit Test"}</span>
                      </button>
                    </div>
                    <pre className="text-indigo-300/90 whitespace-pre-wrap leading-relaxed">
                      {suggestion.testCode || "// Không có test code bổ sung."}
                    </pre>
                  </div>
                </div>
              )}

              {/* TAB 3: Technical Reasoning */}
              {activeTab === "reasoning" && (
                <div className="p-4 rounded-xl bg-zinc-950 border border-zinc-800 space-y-3 text-xs text-zinc-300 leading-relaxed">
                  <h4 className="font-semibold text-white flex items-center gap-1.5">
                    <CheckCircle2 className="w-4 h-4 text-teal-400" />
                    <span>{language === "vi" ? "Tại sao bản vá này an toàn?" : "Why this fix is robust"}</span>
                  </h4>
                  <p>{suggestion.explanation}</p>
                </div>
              )}
            </div>
          ) : (
            <div className="py-12 text-center text-zinc-500 text-xs">
              {language === "vi" ? "Không có dữ liệu đề xuất." : "No suggestion available."}
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-zinc-800 bg-zinc-950/90 flex items-center justify-between">
          <div className="flex items-center gap-1.5 text-xs text-zinc-400">
            <Sparkles className="w-3.5 h-3.5 text-emerald-400" />
            <span>{language === "vi" ? "Mã nguồn được kiểm toán bởi PatchWise Security Engine" : "Powered by PatchWise AI"}</span>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-white text-xs font-medium transition cursor-pointer"
          >
            {language === "vi" ? "Đóng" : "Close"}
          </button>
        </div>
      </div>
    </div>
  );
};
